name: shmr_25
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  fuzzy: ^0.5.1
  dio: ^5.8.0+1
  internet_connection_checker: ^1.0.0
  chart_widget:
    path: ./chart_widget
  worker_manager: ^7.0.0
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  mockito: ^5.4.4
  coverage: ^1.15.0
dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.4.0
  drift_dev: ^2.27.0
  intl_utils: ^2.8.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/onboarding/Splash.png
    - assets/icons/
  generate: true




